/* This file was generated by SableCC (http://www.sablecc.org/). */

package graphlang.parser;

import graphlang.lexer.*;
import graphlang.node.*;
import graphlang.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AProgram */
		    {
			ArrayList list = new0();
			push(goTo(0), list, false);
		    }
		    break;
                    case 1: /* reduce AStmtStmtlist */
		    {
			ArrayList list = new1();
			push(goTo(1), list, false);
		    }
		    break;
                    case 2: /* reduce AListStmtlist */
		    {
			ArrayList list = new2();
			push(goTo(1), list, false);
		    }
		    break;
                    case 3: /* reduce AMoveStmt */
		    {
			ArrayList list = new3();
			push(goTo(2), list, false);
		    }
		    break;
                    case 4: /* reduce ADrawStmt */
		    {
			ArrayList list = new4();
			push(goTo(2), list, false);
		    }
		    break;
                    case 5: /* reduce ADefineDefinegrid */
		    {
			ArrayList list = new5();
			push(goTo(3), list, false);
		    }
		    break;
                    case 6: /* reduce AMoveMove */
		    {
			ArrayList list = new6();
			push(goTo(4), list, false);
		    }
		    break;
                    case 7: /* reduce AConnDraw */
		    {
			ArrayList list = new7();
			push(goTo(5), list, false);
		    }
		    break;
                    case 8: /* reduce ACircDraw */
		    {
			ArrayList list = new8();
			push(goTo(5), list, false);
		    }
		    break;
                    case 9: /* reduce AErasecolDraw */
		    {
			ArrayList list = new9();
			push(goTo(5), list, false);
		    }
		    break;
                    case 10: /* reduce AMakecircleCircle */
		    {
			ArrayList list = new10();
			push(goTo(6), list, false);
		    }
		    break;
                    case 11: /* reduce AMarkConnect */
		    {
			ArrayList list = new11();
			push(goTo(7), list, false);
		    }
		    break;
                    case 12: /* reduce AConnectcolConnect */
		    {
			ArrayList list = new12();
			push(goTo(7), list, false);
		    }
		    break;
                    case 13: /* reduce AChoosecolConnect */
		    {
			ArrayList list = new13();
			push(goTo(7), list, false);
		    }
		    break;
                    case 14: /* reduce AConnectcolorConnectcolor */
		    {
			ArrayList list = new14();
			push(goTo(8), list, false);
		    }
		    break;
                    case 15: /* reduce AChooseChoosecolor */
		    {
			ArrayList list = new15();
			push(goTo(9), list, false);
		    }
		    break;
                    case 16: /* reduce AMarkpoint */
		    {
			ArrayList list = new16();
			push(goTo(10), list, false);
		    }
		    break;
                    case 17: /* reduce AErasecolorErase */
		    {
			ArrayList list = new17();
			push(goTo(11), list, false);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgram node1 = (PProgram) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AProgram */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        PDefinegrid pdefinegridNode2;
        PStmtlist pstmtlistNode3;
        pdefinegridNode2 = (PDefinegrid)nodeArrayList1.get(0);
        pstmtlistNode3 = (PStmtlist)nodeArrayList2.get(0);

        pprogramNode1 = new AProgram(pdefinegridNode2, pstmtlistNode3);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce AStmtStmtlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStmtlist pstmtlistNode1;
        {
            // Block
        PStmt pstmtNode2;
        pstmtNode2 = (PStmt)nodeArrayList1.get(0);

        pstmtlistNode1 = new AStmtStmtlist(pstmtNode2);
        }
	nodeList.add(pstmtlistNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce AListStmtlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStmtlist pstmtlistNode1;
        {
            // Block
        PStmt pstmtNode2;
        PStmtlist pstmtlistNode3;
        pstmtNode2 = (PStmt)nodeArrayList1.get(0);
        pstmtlistNode3 = (PStmtlist)nodeArrayList2.get(0);

        pstmtlistNode1 = new AListStmtlist(pstmtNode2, pstmtlistNode3);
        }
	nodeList.add(pstmtlistNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce AMoveStmt */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStmt pstmtNode1;
        {
            // Block
        PMove pmoveNode2;
        pmoveNode2 = (PMove)nodeArrayList1.get(0);

        pstmtNode1 = new AMoveStmt(pmoveNode2);
        }
	nodeList.add(pstmtNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce ADrawStmt */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStmt pstmtNode1;
        {
            // Block
        PDraw pdrawNode2;
        pdrawNode2 = (PDraw)nodeArrayList1.get(0);

        pstmtNode1 = new ADrawStmt(pdrawNode2);
        }
	nodeList.add(pstmtNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce ADefineDefinegrid */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PDefinegrid pdefinegridNode1;
        {
            // Block
        TKeywordmake tkeywordmakeNode2;
        TNumber tnumberNode3;
        tkeywordmakeNode2 = (TKeywordmake)nodeArrayList1.get(0);
        tnumberNode3 = (TNumber)nodeArrayList2.get(0);

        pdefinegridNode1 = new ADefineDefinegrid(tkeywordmakeNode2, tnumberNode3);
        }
	nodeList.add(pdefinegridNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce AMoveMove */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMove pmoveNode1;
        {
            // Block
        TKeywordmove tkeywordmoveNode2;
        TDirection tdirectionNode3;
        TNumber tnumberNode4;
        tkeywordmoveNode2 = (TKeywordmove)nodeArrayList1.get(0);
        tdirectionNode3 = (TDirection)nodeArrayList2.get(0);
        tnumberNode4 = (TNumber)nodeArrayList3.get(0);

        pmoveNode1 = new AMoveMove(tkeywordmoveNode2, tdirectionNode3, tnumberNode4);
        }
	nodeList.add(pmoveNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce AConnDraw */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PDraw pdrawNode1;
        {
            // Block
        PConnect pconnectNode2;
        pconnectNode2 = (PConnect)nodeArrayList1.get(0);

        pdrawNode1 = new AConnDraw(pconnectNode2);
        }
	nodeList.add(pdrawNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce ACircDraw */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PDraw pdrawNode1;
        {
            // Block
        PCircle pcircleNode2;
        pcircleNode2 = (PCircle)nodeArrayList1.get(0);

        pdrawNode1 = new ACircDraw(pcircleNode2);
        }
	nodeList.add(pdrawNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce AErasecolDraw */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PDraw pdrawNode1;
        {
            // Block
        PErase peraseNode2;
        peraseNode2 = (PErase)nodeArrayList1.get(0);

        pdrawNode1 = new AErasecolDraw(peraseNode2);
        }
	nodeList.add(pdrawNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new10() /* reduce AMakecircleCircle */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCircle pcircleNode1;
        {
            // Block
        TKeywordcircle tkeywordcircleNode2;
        TColor tcolorNode3;
        TNumber tnumberNode4;
        tkeywordcircleNode2 = (TKeywordcircle)nodeArrayList1.get(0);
        tcolorNode3 = (TColor)nodeArrayList2.get(0);
        tnumberNode4 = (TNumber)nodeArrayList3.get(0);

        pcircleNode1 = new AMakecircleCircle(tkeywordcircleNode2, tcolorNode3, tnumberNode4);
        }
	nodeList.add(pcircleNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new11() /* reduce AMarkConnect */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PConnect pconnectNode1;
        {
            // Block
        PMarkpoint pmarkpointNode2;
        pmarkpointNode2 = (PMarkpoint)nodeArrayList1.get(0);

        pconnectNode1 = new AMarkConnect(pmarkpointNode2);
        }
	nodeList.add(pconnectNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new12() /* reduce AConnectcolConnect */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PConnect pconnectNode1;
        {
            // Block
        PConnectcolor pconnectcolorNode2;
        pconnectcolorNode2 = (PConnectcolor)nodeArrayList1.get(0);

        pconnectNode1 = new AConnectcolConnect(pconnectcolorNode2);
        }
	nodeList.add(pconnectNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new13() /* reduce AChoosecolConnect */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PConnect pconnectNode1;
        {
            // Block
        PChoosecolor pchoosecolorNode2;
        pchoosecolorNode2 = (PChoosecolor)nodeArrayList1.get(0);

        pconnectNode1 = new AChoosecolConnect(pchoosecolorNode2);
        }
	nodeList.add(pconnectNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new14() /* reduce AConnectcolorConnectcolor */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PConnectcolor pconnectcolorNode1;
        {
            // Block
        TKeywordconnect tkeywordconnectNode2;
        TColor tcolorNode3;
        TShape tshapeNode4;
        tkeywordconnectNode2 = (TKeywordconnect)nodeArrayList1.get(0);
        tcolorNode3 = (TColor)nodeArrayList2.get(0);
        tshapeNode4 = (TShape)nodeArrayList3.get(0);

        pconnectcolorNode1 = new AConnectcolorConnectcolor(tkeywordconnectNode2, tcolorNode3, tshapeNode4);
        }
	nodeList.add(pconnectcolorNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new15() /* reduce AChooseChoosecolor */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PChoosecolor pchoosecolorNode1;
        {
            // Block
        TKeywordchoose tkeywordchooseNode2;
        TColor tcolorNode3;
        tkeywordchooseNode2 = (TKeywordchoose)nodeArrayList1.get(0);
        tcolorNode3 = (TColor)nodeArrayList2.get(0);

        pchoosecolorNode1 = new AChooseChoosecolor(tkeywordchooseNode2, tcolorNode3);
        }
	nodeList.add(pchoosecolorNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new16() /* reduce AMarkpoint */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMarkpoint pmarkpointNode1;
        {
            // Block
        TKeywordmark tkeywordmarkNode2;
        tkeywordmarkNode2 = (TKeywordmark)nodeArrayList1.get(0);

        pmarkpointNode1 = new AMarkpoint(tkeywordmarkNode2);
        }
	nodeList.add(pmarkpointNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new17() /* reduce AErasecolorErase */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PErase peraseNode1;
        {
            // Block
        TKeyworderase tkeyworderaseNode2;
        TColor tcolorNode3;
        tkeyworderaseNode2 = (TKeyworderase)nodeArrayList1.get(0);
        tcolorNode3 = (TColor)nodeArrayList2.get(0);

        peraseNode1 = new AErasecolorErase(tkeyworderaseNode2, tcolorNode3);
        }
	nodeList.add(peraseNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {1, SHIFT, 1}, },
			{{-1, ERROR, 1}, {10, SHIFT, 4}, },
			{{-1, ERROR, 2}, {14, ACCEPT, -1}, },
			{{-1, ERROR, 3}, {0, SHIFT, 5}, {2, SHIFT, 6}, {3, SHIFT, 7}, {4, SHIFT, 8}, {5, SHIFT, 9}, {6, SHIFT, 10}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 5}, {7, SHIFT, 21}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 7}, {8, SHIFT, 22}, },
			{{-1, ERROR, 8}, {8, SHIFT, 23}, },
			{{-1, ERROR, 9}, {8, SHIFT, 24}, },
			{{-1, ERROR, 10}, {8, SHIFT, 25}, },
			{{-1, REDUCE, 0}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 5}, {2, SHIFT, 6}, {3, SHIFT, 7}, {4, SHIFT, 8}, {5, SHIFT, 9}, {6, SHIFT, 10}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 21}, {10, SHIFT, 27}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 23}, {9, SHIFT, 28}, },
			{{-1, ERROR, 24}, {10, SHIFT, 29}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 10}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 11}, {12, 26}, },
			{{-1, 12}, },
			{{-1, 3}, },
			{{-1, 13}, },
			{{-1, 14}, },
			{{-1, 15}, },
			{{-1, 16}, },
			{{-1, 17}, },
			{{-1, 18}, },
			{{-1, 19}, },
			{{-1, 20}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'MAKE'",
			"expecting: number",
			"expecting: EOF",
			"expecting: 'MOVE', 'MARK', 'CHOOSE', 'CONNECT', 'CIRCLE', 'ERASE'",
			"expecting: direction",
			"expecting: 'MOVE', 'MARK', 'CHOOSE', 'CONNECT', 'CIRCLE', 'ERASE', EOF",
			"expecting: color",
			"expecting: shape",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 4, 5, 6, 6, 6, 6, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 7, 1, 5, 2, 5, 5, 5, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
