/* This file was generated by SableCC (http://www.sablecc.org/). */

package graphlang.node;

import graphlang.analysis.*;

@SuppressWarnings("nls")
public final class ACircDraw extends PDraw
{
    private PCircle _circle_;

    public ACircDraw()
    {
        // Constructor
    }

    public ACircDraw(
        @SuppressWarnings("hiding") PCircle _circle_)
    {
        // Constructor
        setCircle(_circle_);

    }

    @Override
    public Object clone()
    {
        return new ACircDraw(
            cloneNode(this._circle_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACircDraw(this);
    }

    public PCircle getCircle()
    {
        return this._circle_;
    }

    public void setCircle(PCircle node)
    {
        if(this._circle_ != null)
        {
            this._circle_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._circle_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._circle_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._circle_ == child)
        {
            this._circle_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._circle_ == oldChild)
        {
            setCircle((PCircle) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
