/* This file was generated by SableCC (http://www.sablecc.org/). */

package graphlang.node;

import graphlang.analysis.*;

@SuppressWarnings("nls")
public final class ADrawStmt extends PStmt
{
    private PDraw _draw_;

    public ADrawStmt()
    {
        // Constructor
    }

    public ADrawStmt(
        @SuppressWarnings("hiding") PDraw _draw_)
    {
        // Constructor
        setDraw(_draw_);

    }

    @Override
    public Object clone()
    {
        return new ADrawStmt(
            cloneNode(this._draw_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADrawStmt(this);
    }

    public PDraw getDraw()
    {
        return this._draw_;
    }

    public void setDraw(PDraw node)
    {
        if(this._draw_ != null)
        {
            this._draw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._draw_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._draw_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._draw_ == child)
        {
            this._draw_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._draw_ == oldChild)
        {
            setDraw((PDraw) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
