/* This file was generated by SableCC (http://www.sablecc.org/). */

package graphlang.node;

import graphlang.analysis.*;

@SuppressWarnings("nls")
public final class AErasecolDraw extends PDraw
{
    private PErase _erase_;

    public AErasecolDraw()
    {
        // Constructor
    }

    public AErasecolDraw(
        @SuppressWarnings("hiding") PErase _erase_)
    {
        // Constructor
        setErase(_erase_);

    }

    @Override
    public Object clone()
    {
        return new AErasecolDraw(
            cloneNode(this._erase_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAErasecolDraw(this);
    }

    public PErase getErase()
    {
        return this._erase_;
    }

    public void setErase(PErase node)
    {
        if(this._erase_ != null)
        {
            this._erase_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._erase_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._erase_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._erase_ == child)
        {
            this._erase_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._erase_ == oldChild)
        {
            setErase((PErase) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
