/* This file was generated by SableCC (http://www.sablecc.org/). */

package graphlang.node;

import graphlang.analysis.*;

@SuppressWarnings("nls")
public final class AFillStmt extends PStmt
{
    private PColorize _colorize_;

    public AFillStmt()
    {
        // Constructor
    }

    public AFillStmt(
        @SuppressWarnings("hiding") PColorize _colorize_)
    {
        // Constructor
        setColorize(_colorize_);

    }

    @Override
    public Object clone()
    {
        return new AFillStmt(
            cloneNode(this._colorize_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFillStmt(this);
    }

    public PColorize getColorize()
    {
        return this._colorize_;
    }

    public void setColorize(PColorize node)
    {
        if(this._colorize_ != null)
        {
            this._colorize_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colorize_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colorize_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colorize_ == child)
        {
            this._colorize_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colorize_ == oldChild)
        {
            setColorize((PColorize) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
