/* This file was generated by SableCC (http://www.sablecc.org/). */

package graphlang.node;

import graphlang.analysis.*;

@SuppressWarnings("nls")
public final class AMarkConnect extends PConnect
{
    private PMarkpoint _markpoint_;

    public AMarkConnect()
    {
        // Constructor
    }

    public AMarkConnect(
        @SuppressWarnings("hiding") PMarkpoint _markpoint_)
    {
        // Constructor
        setMarkpoint(_markpoint_);

    }

    @Override
    public Object clone()
    {
        return new AMarkConnect(
            cloneNode(this._markpoint_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMarkConnect(this);
    }

    public PMarkpoint getMarkpoint()
    {
        return this._markpoint_;
    }

    public void setMarkpoint(PMarkpoint node)
    {
        if(this._markpoint_ != null)
        {
            this._markpoint_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._markpoint_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._markpoint_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._markpoint_ == child)
        {
            this._markpoint_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._markpoint_ == oldChild)
        {
            setMarkpoint((PMarkpoint) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
