/* This file was generated by SableCC (http://www.sablecc.org/). */

package graphlang.node;

import graphlang.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private PDefinegrid _definegrid_;
    private PStmtlist _stmtlist_;

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") PDefinegrid _definegrid_,
        @SuppressWarnings("hiding") PStmtlist _stmtlist_)
    {
        // Constructor
        setDefinegrid(_definegrid_);

        setStmtlist(_stmtlist_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneNode(this._definegrid_),
            cloneNode(this._stmtlist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public PDefinegrid getDefinegrid()
    {
        return this._definegrid_;
    }

    public void setDefinegrid(PDefinegrid node)
    {
        if(this._definegrid_ != null)
        {
            this._definegrid_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definegrid_ = node;
    }

    public PStmtlist getStmtlist()
    {
        return this._stmtlist_;
    }

    public void setStmtlist(PStmtlist node)
    {
        if(this._stmtlist_ != null)
        {
            this._stmtlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmtlist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._definegrid_)
            + toString(this._stmtlist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._definegrid_ == child)
        {
            this._definegrid_ = null;
            return;
        }

        if(this._stmtlist_ == child)
        {
            this._stmtlist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._definegrid_ == oldChild)
        {
            setDefinegrid((PDefinegrid) newChild);
            return;
        }

        if(this._stmtlist_ == oldChild)
        {
            setStmtlist((PStmtlist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
