/* This file was generated by SableCC (http://www.sablecc.org/). */

package graphlang.node;

import graphlang.analysis.*;

@SuppressWarnings("nls")
public final class AStmt extends PStmt
{
    private PMove _move_;

    public AStmt()
    {
        // Constructor
    }

    public AStmt(
        @SuppressWarnings("hiding") PMove _move_)
    {
        // Constructor
        setMove(_move_);

    }

    @Override
    public Object clone()
    {
        return new AStmt(
            cloneNode(this._move_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStmt(this);
    }

    public PMove getMove()
    {
        return this._move_;
    }

    public void setMove(PMove node)
    {
        if(this._move_ != null)
        {
            this._move_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._move_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._move_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._move_ == child)
        {
            this._move_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._move_ == oldChild)
        {
            setMove((PMove) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
