/* This file was generated by SableCC (http://www.sablecc.org/). */

package graphlang.lexer;

import java.io.*;
import graphlang.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKeywordgrid(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKeywordmove(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKeywordmark(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKeywordchoose(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKeywordconnect(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKeywordcircle(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKeywordfill(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKeyworderase(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDirection(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColor(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColoropt(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShape(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }
    Token new13(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOpsemicolon(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOpequal(line, pos); }
    Token new16(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{10, 10, 1}, {13, 13, 2}, {32, 32, 3}, {45, 45, 4}, {48, 57, 5}, {59, 59, 6}, {61, 61, 7}, {65, 65, 8}, {66, 66, 9}, {67, 67, 10}, {68, 68, 11}, {69, 69, 12}, {70, 70, 13}, {71, 71, 14}, {72, 75, 8}, {76, 76, 15}, {77, 77, 16}, {78, 81, 8}, {82, 82, 17}, {83, 83, 18}, {84, 84, 8}, {85, 85, 19}, {86, 90, 8}, {97, 97, 20}, {98, 98, 21}, {99, 99, 22}, {100, 100, 23}, {101, 101, 24}, {102, 102, 25}, {103, 103, 26}, {104, 107, 20}, {108, 108, 27}, {109, 109, 28}, {110, 113, 20}, {114, 114, 29}, {115, 115, 30}, {116, 116, 20}, {117, 117, 31}, {118, 122, 20}, },
            {{10, 32, -2}, },
            {{10, 32, -2}, },
            {{10, 32, -2}, },
            {},
            {{48, 57, 5}, },
            {},
            {},
            {{65, 90, 8}, {97, 122, 20}, },
            {{65, 75, 8}, {76, 76, 32}, {77, 90, 8}, {97, 107, 20}, {108, 108, 33}, {109, 122, 20}, },
            {{65, 71, 8}, {72, 72, 34}, {73, 73, 35}, {74, 78, 8}, {79, 79, 36}, {80, 84, 8}, {85, 85, 37}, {86, 90, 8}, {97, 103, 20}, {104, 104, 38}, {105, 105, 39}, {106, 110, 20}, {111, 111, 40}, {112, 116, 20}, {117, 117, 41}, {118, 122, 20}, },
            {{65, 78, 8}, {79, 79, 42}, {80, 90, 8}, {97, 110, 20}, {111, 111, 43}, {112, 122, 20}, },
            {{65, 81, 8}, {82, 82, 44}, {83, 90, 8}, {97, 113, 20}, {114, 114, 45}, {115, 122, 20}, },
            {{65, 72, 8}, {73, 73, 46}, {74, 90, 8}, {97, 104, 20}, {105, 105, 47}, {106, 122, 20}, },
            {{65, 81, 8}, {82, 82, 48}, {83, 113, -14}, {114, 114, 49}, {115, 122, 20}, },
            {{65, 68, 8}, {69, 69, 50}, {70, 90, 8}, {97, 100, 20}, {101, 101, 51}, {102, 122, 20}, },
            {{65, 65, 52}, {66, 78, 8}, {79, 79, 53}, {80, 90, 8}, {97, 97, 54}, {98, 110, 20}, {111, 111, 55}, {112, 122, 20}, },
            {{65, 68, 8}, {69, 69, 56}, {70, 72, 8}, {73, 73, 57}, {74, 90, 8}, {97, 100, 20}, {101, 101, 58}, {102, 104, 20}, {105, 105, 59}, {106, 122, 20}, },
            {{65, 83, 8}, {84, 84, 60}, {85, 90, 8}, {97, 115, 20}, {116, 116, 61}, {117, 122, 20}, },
            {{65, 79, 8}, {80, 80, 62}, {81, 90, 8}, {97, 111, 20}, {112, 112, 63}, {113, 122, 20}, },
            {{65, 122, -10}, },
            {{65, 122, -11}, },
            {{65, 122, -12}, },
            {{65, 122, -13}, },
            {{65, 122, -14}, },
            {{65, 122, -15}, },
            {{65, 122, -16}, },
            {{65, 122, -17}, },
            {{65, 122, -18}, },
            {{65, 122, -19}, },
            {{65, 122, -20}, },
            {{65, 122, -21}, },
            {{65, 84, 8}, {85, 85, 64}, {86, 90, 8}, {97, 116, 20}, {117, 117, 65}, {118, 122, 20}, },
            {{65, 122, -34}, },
            {{65, 78, 8}, {79, 79, 66}, {80, 110, -13}, {111, 111, 67}, {112, 122, 20}, },
            {{65, 81, 8}, {82, 82, 68}, {83, 113, -14}, {114, 114, 69}, {115, 122, 20}, },
            {{65, 77, 8}, {78, 78, 70}, {79, 90, 8}, {97, 109, 20}, {110, 110, 71}, {111, 122, 20}, },
            {{65, 81, 8}, {82, 82, 72}, {83, 113, -14}, {114, 114, 73}, {115, 122, 20}, },
            {{65, 122, -36}, },
            {{65, 122, -37}, },
            {{65, 122, -38}, },
            {{65, 122, -39}, },
            {{65, 86, 8}, {87, 87, 74}, {88, 90, 8}, {97, 118, 20}, {119, 119, 75}, {120, 122, 20}, },
            {{65, 122, -44}, },
            {{65, 65, 76}, {66, 90, 8}, {97, 97, 77}, {98, 122, 20}, },
            {{65, 122, -46}, },
            {{65, 75, 8}, {76, 76, 78}, {77, 107, -11}, {108, 108, 79}, {109, 122, 20}, },
            {{65, 122, -48}, },
            {{65, 68, 8}, {69, 69, 80}, {70, 72, 8}, {73, 73, 81}, {74, 100, -19}, {101, 101, 82}, {102, 104, 20}, {105, 105, 83}, {106, 122, 20}, },
            {{65, 122, -50}, },
            {{65, 69, 8}, {70, 70, 84}, {71, 90, 8}, {97, 101, 20}, {102, 102, 85}, {103, 122, 20}, },
            {{65, 122, -52}, },
            {{65, 81, 8}, {82, 82, 86}, {83, 113, -14}, {114, 114, 87}, {115, 122, 20}, },
            {{65, 85, 8}, {86, 86, 88}, {87, 90, 8}, {97, 117, 20}, {118, 118, 89}, {119, 122, 20}, },
            {{65, 122, -54}, },
            {{65, 122, -55}, },
            {{65, 67, 8}, {68, 68, 90}, {69, 90, 8}, {97, 99, 20}, {100, 100, 91}, {101, 122, 20}, },
            {{65, 70, 8}, {71, 71, 92}, {72, 90, 8}, {97, 102, 20}, {103, 103, 93}, {104, 122, 20}, },
            {{65, 122, -58}, },
            {{65, 122, -59}, },
            {{65, 81, 8}, {82, 82, 94}, {83, 113, -14}, {114, 114, 95}, {115, 122, 20}, },
            {{65, 122, -62}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 68, 8}, {69, 69, 96}, {70, 100, -17}, {101, 101, 97}, {102, 122, 20}, },
            {{65, 122, -66}, },
            {{65, 78, 8}, {79, 79, 98}, {80, 110, -13}, {111, 111, 99}, {112, 122, 20}, },
            {{65, 122, -68}, },
            {{65, 66, 8}, {67, 67, 100}, {68, 90, 8}, {97, 98, 20}, {99, 99, 101}, {100, 122, 20}, },
            {{65, 122, -70}, },
            {{65, 77, 8}, {78, 78, 102}, {79, 109, -38}, {110, 110, 103}, {111, 122, 20}, },
            {{65, 122, -72}, },
            {{65, 85, 8}, {86, 86, 104}, {87, 117, -55}, {118, 118, 105}, {119, 122, 20}, },
            {{65, 122, -74}, },
            {{65, 77, 8}, {78, 78, 106}, {79, 109, -38}, {110, 110, 107}, {111, 122, 20}, },
            {{65, 122, -76}, },
            {{65, 82, 8}, {83, 83, 108}, {84, 90, 8}, {97, 114, 20}, {115, 115, 109}, {116, 122, 20}, },
            {{65, 122, -78}, },
            {{65, 75, 8}, {76, 76, 110}, {77, 107, -11}, {108, 108, 111}, {109, 122, 20}, },
            {{65, 122, -80}, },
            {{65, 68, 8}, {69, 69, 112}, {70, 100, -17}, {101, 101, 113}, {102, 122, 20}, },
            {{65, 67, 8}, {68, 68, 114}, {69, 99, -58}, {100, 100, 115}, {101, 122, 20}, },
            {{65, 122, -82}, },
            {{65, 122, -83}, },
            {{65, 83, 8}, {84, 84, 116}, {85, 115, -20}, {116, 116, 117}, {117, 122, 20}, },
            {{65, 122, -86}, },
            {{65, 74, 8}, {75, 75, 118}, {76, 90, 8}, {97, 106, 20}, {107, 107, 119}, {108, 122, 20}, },
            {{65, 122, -88}, },
            {{65, 68, 8}, {69, 69, 120}, {70, 100, -17}, {101, 101, 121}, {102, 122, 20}, },
            {{65, 122, -90}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 71, 8}, {72, 72, 122}, {73, 90, 8}, {97, 103, 20}, {104, 104, 123}, {105, 122, 20}, },
            {{65, 122, -94}, },
            {{65, 65, 124}, {66, 90, 8}, {97, 97, 125}, {98, 122, 20}, },
            {{65, 122, -96}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 82, 8}, {83, 83, 126}, {84, 114, -78}, {115, 115, 127}, {116, 122, 20}, },
            {{65, 122, -100}, },
            {{65, 75, 8}, {76, 76, 128}, {77, 107, -11}, {108, 108, 129}, {109, 122, 20}, },
            {{65, 122, -102}, },
            {{65, 68, 8}, {69, 69, 130}, {70, 100, -17}, {101, 101, 131}, {102, 122, 20}, },
            {{65, 122, -104}, },
            {{65, 68, 8}, {69, 69, 132}, {70, 100, -17}, {101, 101, 133}, {102, 122, 20}, },
            {{65, 122, -106}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 68, 8}, {69, 69, 134}, {70, 100, -17}, {101, 101, 135}, {102, 122, 20}, },
            {{65, 122, -110}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 77, 8}, {78, 78, 136}, {79, 109, -38}, {110, 110, 137}, {111, 122, 20}, },
            {{65, 122, -114}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 83, 8}, {84, 84, 138}, {85, 115, -20}, {116, 116, 139}, {117, 122, 20}, },
            {{65, 122, -124}, },
            {{65, 72, 8}, {73, 73, 140}, {74, 104, -15}, {105, 105, 141}, {106, 122, 20}, },
            {{65, 122, -126}, },
            {{65, 68, 8}, {69, 69, 142}, {70, 100, -17}, {101, 101, 143}, {102, 122, 20}, },
            {{65, 122, -128}, },
            {{65, 68, 8}, {69, 69, 144}, {70, 100, -17}, {101, 101, 145}, {102, 122, 20}, },
            {{65, 122, -130}, },
            {{65, 66, 8}, {67, 67, 146}, {68, 98, -70}, {99, 99, 147}, {100, 122, 20}, },
            {{65, 122, -132}, },
            {{65, 67, 8}, {68, 68, 148}, {69, 99, -58}, {100, 100, 149}, {101, 122, 20}, },
            {{65, 122, -134}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 70, 8}, {71, 71, 150}, {72, 102, -59}, {103, 103, 151}, {104, 122, 20}, },
            {{65, 122, -142}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 83, 8}, {84, 84, 152}, {85, 115, -20}, {116, 116, 153}, {117, 122, 20}, },
            {{65, 122, -148}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 71, 8}, {72, 72, 154}, {73, 103, -94}, {104, 104, 155}, {105, 122, 20}, },
            {{65, 122, -152}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 83, 8}, {84, 84, 156}, {85, 115, -20}, {116, 116, 157}, {117, 122, 20}, },
            {{65, 122, -156}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 16, 16, 16, 17, 12, 14, 15, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 8, 8, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 9, 9, 13, 13, 13, 13, 9, 9, 13, 13, 13, 13, 13, 13, 13, 13, 8, 8, 13, 13, 6, 6, 13, 13, 0, 0, 8, 8, 2, 2, 1, 1, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 7, 7, 9, 9, 8, 8, 13, 13, 3, 3, 5, 5, 13, 13, 11, 11, 13, 13, 4, 4, 13, 13, 11, 11, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
